import type { FinanceSnapshot, FinanceTransaction } from "@/types/finance";
import { defaultCategories } from "./categories";

const now = "2026-07-16T09:41:00+08:00";

const transactions: FinanceTransaction[] = [
  {
    id: "trx-001",
    type: "income",
    destination: "split",
    totalAmount: 3500,
    dailyAmount: 2450,
    savingsAmount: 1050,
    categoryId: "income-salary",
    note: "Gaji Julai",
    transactionDate: "2026-07-16",
    transactionTime: "09:10",
    createdAt: now,
  },
  {
    id: "trx-002",
    type: "expense",
    destination: "daily",
    totalAmount: 25.8,
    dailyAmount: 25.8,
    savingsAmount: 0,
    categoryId: "expense-food",
    note: "Sarapan dan kopi",
    transactionDate: "2026-07-16",
    transactionTime: "08:30",
    createdAt: now,
  },
  {
    id: "trx-003",
    type: "expense",
    destination: "daily",
    totalAmount: 64.2,
    dailyAmount: 64.2,
    savingsAmount: 0,
    categoryId: "expense-transport",
    note: "MRT dan e-hailing",
    transactionDate: "2026-07-15",
    transactionTime: "18:40",
    createdAt: now,
  },
  {
    id: "trx-004",
    type: "income",
    destination: "savings",
    totalAmount: 450,
    dailyAmount: 0,
    savingsAmount: 450,
    categoryId: "income-dividend",
    note: "Dividen",
    transactionDate: "2026-07-14",
    transactionTime: "13:20",
    createdAt: now,
  },
  {
    id: "trx-005",
    type: "expense",
    destination: "savings",
    totalAmount: 120,
    dailyAmount: 0,
    savingsAmount: 120,
    categoryId: "expense-education",
    note: "Kursus",
    transactionDate: "2026-07-13",
    transactionTime: "21:12",
    createdAt: now,
  },
  {
    id: "trx-006",
    type: "expense",
    destination: "daily",
    totalAmount: 310,
    dailyAmount: 310,
    savingsAmount: 0,
    categoryId: "expense-bills",
    note: "Bil utiliti",
    transactionDate: "2026-07-11",
    transactionTime: "10:00",
    createdAt: now,
  },
  {
    id: "trx-007",
    type: "income",
    destination: "daily",
    totalAmount: 320,
    dailyAmount: 320,
    savingsAmount: 0,
    categoryId: "income-freelance",
    note: "Projek kecil",
    transactionDate: "2026-07-09",
    transactionTime: "16:45",
    createdAt: now,
  },
];

export function getDemoSnapshot(): FinanceSnapshot {
  return {
    profile: {
      displayName: "Syahmi",
      currency: "MYR",
      timezone: "Asia/Kuala_Lumpur",
    },
    balances: {
      dailyBalance: 4900,
      savingsBalance: 7170,
    },
    categories: defaultCategories,
    transactions,
  };
}
